[package]
name = "inspirer-content"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "inspirer-content-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "inspirer-content-simple-service"
path = "src/bin/simple_server.rs"

[dependencies]
sqlx = { version = "0.5", features = ["mysql", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
strum = { version = "0.21", features = ["derive"] }
anyhow = "1.0"
inspirer-query-ext = { path = "../support/query-ext", default-features = false }
thiserror = "1.0"
rustyline = "8"
structopt = "0.3"
tokio = { version = "~1.8", features = ["rt", "macros", "rt-multi-thread"] }
axum = { version = "0.1" }

[features]
default = ["runtime-actix-rustls"]
runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls", "inspirer-query-ext/runtime-actix-native-tls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls", "inspirer-query-ext/runtime-async-std-native-tls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls", "inspirer-query-ext/runtime-tokio-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls", "inspirer-query-ext/runtime-actix-rustls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls", "inspirer-query-ext/runtime-async-std-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls", "inspirer-query-ext/runtime-tokio-rustls"]