[package]
name = "inspirer-common"
version = "0.1.0"
authors = ["chongyi <xpz3847878@163.com>"]
edition = "2018"

[dependencies]
sha-1 = "^0.8"
sha2 = "^0.8"
md-5 = "^0.8"
digest = "^0.8"
hex = "*"
generic-array = "0.12.3"